sudo: false

language: php
php:
  - 7.2

services:
  docker

script:
  - cp .env.travis .env
  - composer create-project --prefer-dist laravel/laravel .laravel "5.8.*"
  - ./build.sh
  - cp Dockerfile docker-compose.yml .laravel
  - cd .laravel && docker-compose run app phpunit

cache:
  directories:
    - $HOME/.composer/cache
