sudo: false

services:
  docker

script:
  - cp .env.travis .env
  - composer create-project laravel/laravel --prefer-dist .laravel
  - cd .laravel && composer install
  - ./build.sh
  - cp Dockerfile docker-compose.yml .laravel

cache:
  directories:
    - $HOME/.composer/cache
